### ISSUE TITLE
Supporting Swift Package Manager?

### ISSUE THREAD

**Issue by tristanl-slalom** [wl-online-payments-direct/sdk-client-swift#1]
Is there a plan to support Swift Package Manager? Our project is targeting trying to use SPM for every reference, at least as much as possible.

Thank you!

**Comment by worldline-direct-support-team** [comment]
Thank you for reaching out. 
We are indeed looking to support Swift Package Manager in the future. We will post an update in this issue once the SDK is available on Swift Package Manager.

**Comment by worldline-direct-support-team** [comment]
Hello trisco2001,

We've released a new version of the SDK that contains support for Swift Package Manager. Follow the steps in the README to include.

Kind regards,
Worldline Support
